# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annual', '0002_auto_20170131_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualmean',
            name='url',
            field=models.CharField(default='', max_length=50),
        ),
    ]
