# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annual', '0006_auto_20170202_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualmean',
            name='aqiurl',
            field=models.CharField(default='', max_length=200),
        ),
    ]
