# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 08:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annual', '0010_dailymean_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailymean',
            old_name='url',
            new_name='site_url',
        ),
    ]
