# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 09:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annual', '0011_auto_20170205_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annualmean',
            old_name='concentration',
            new_name='Concentration',
        ),
        migrations.RenameField(
            model_name='annualmean',
            old_name='pollutant',
            new_name='Pollutant',
        ),
        migrations.RenameField(
            model_name='annualmean',
            old_name='site',
            new_name='Site',
        ),
        migrations.RenameField(
            model_name='annualmean',
            old_name='year',
            new_name='Year',
        ),
        migrations.RenameField(
            model_name='dailymean',
            old_name='concentration',
            new_name='Concentration',
        ),
        migrations.RenameField(
            model_name='dailymean',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='dailymean',
            old_name='pollutant',
            new_name='Pollutant',
        ),
        migrations.RenameField(
            model_name='dailymean',
            old_name='site',
            new_name='Site',
        ),
    ]
