# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annual', '0013_remove_dailymean_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailymean',
            name='Concentration',
            field=models.FloatField(max_length=10, null=True),
        ),
    ]
