# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 00:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annual', '0015_dailymean_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailymean',
            old_name='site_url',
            new_name='url',
        ),
    ]
