# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annual', '0016_auto_20170207_0735'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymean',
            name='pollurl',
            field=models.CharField(default='', max_length=50),
        ),
    ]
