# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annual', '0018_auto_20170209_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualmean',
            name='poll',
            field=models.CharField(default='', max_length=50),
        ),
    ]
