# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annual', '0019_annualmean_poll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annualmean',
            name='Concentration',
            field=models.FloatField(max_length=20),
        ),
        migrations.AlterField(
            model_name='annualmean',
            name='Pollutant',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='annualmean',
            name='aqi',
            field=models.CharField(default='', max_length=500),
        ),
    ]
