# Generated by Django 2.0 on 2018-01-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('born', models.DateTimeField()),
                ('name', models.CharField(max_length=50)),
                ('diet', models.CharField(blank=True, max_length=50)),
                ('owner', models.ForeignKey(on_delete='CASCADE', to='app.Person')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
