# Generated by Django 2.0 on 2018-01-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ownable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ownable',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='acquired',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='has_feathers',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='lays_eggs',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='needs_heat',
        ),
        migrations.AddField(
            model_name='pet',
            name='diet',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
